/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AccountAbstractionGuardianInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canSpend"
      | "globalDailyLimit"
      | "limits"
      | "owner"
      | "pauseAccount"
      | "pausedAccounts"
      | "recordSpend"
      | "renounceOwnership"
      | "setAccountLimit"
      | "setGlobalDailyLimit"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountPaused"
      | "DailyLimitUpdated"
      | "OwnershipTransferred"
      | "SpendRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canSpend",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "limits", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseAccount",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "pausedAccounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSpend",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAccountLimit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "canSpend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "globalDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "limits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pausedAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAccountLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AccountPausedEvent {
  export type InputTuple = [account: AddressLike, paused: boolean];
  export type OutputTuple = [account: string, paused: boolean];
  export interface OutputObject {
    account: string;
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyLimitUpdatedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendRecordedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccountAbstractionGuardian extends BaseContract {
  connect(runner?: ContractRunner | null): AccountAbstractionGuardian;
  waitForDeployment(): Promise<this>;

  interface: AccountAbstractionGuardianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canSpend: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish, limit: BigNumberish],
    [boolean],
    "view"
  >;

  globalDailyLimit: TypedContractMethod<[], [bigint], "view">;

  limits: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { usedToday: bigint; lastReset: bigint }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pauseAccount: TypedContractMethod<
    [account: AddressLike, paused: boolean],
    [void],
    "nonpayable"
  >;

  pausedAccounts: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  recordSpend: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish, limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAccountLimit: TypedContractMethod<
    [account: AddressLike, limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGlobalDailyLimit: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canSpend"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish, limit: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "limits"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { usedToday: bigint; lastReset: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseAccount"
  ): TypedContractMethod<
    [account: AddressLike, paused: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pausedAccounts"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordSpend"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish, limit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAccountLimit"
  ): TypedContractMethod<
    [account: AddressLike, limit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGlobalDailyLimit"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccountPaused"
  ): TypedContractEvent<
    AccountPausedEvent.InputTuple,
    AccountPausedEvent.OutputTuple,
    AccountPausedEvent.OutputObject
  >;
  getEvent(
    key: "DailyLimitUpdated"
  ): TypedContractEvent<
    DailyLimitUpdatedEvent.InputTuple,
    DailyLimitUpdatedEvent.OutputTuple,
    DailyLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SpendRecorded"
  ): TypedContractEvent<
    SpendRecordedEvent.InputTuple,
    SpendRecordedEvent.OutputTuple,
    SpendRecordedEvent.OutputObject
  >;

  filters: {
    "AccountPaused(address,bool)": TypedContractEvent<
      AccountPausedEvent.InputTuple,
      AccountPausedEvent.OutputTuple,
      AccountPausedEvent.OutputObject
    >;
    AccountPaused: TypedContractEvent<
      AccountPausedEvent.InputTuple,
      AccountPausedEvent.OutputTuple,
      AccountPausedEvent.OutputObject
    >;

    "DailyLimitUpdated(address,uint256)": TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;
    DailyLimitUpdated: TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SpendRecorded(address,uint256)": TypedContractEvent<
      SpendRecordedEvent.InputTuple,
      SpendRecordedEvent.OutputTuple,
      SpendRecordedEvent.OutputObject
    >;
    SpendRecorded: TypedContractEvent<
      SpendRecordedEvent.InputTuple,
      SpendRecordedEvent.OutputTuple,
      SpendRecordedEvent.OutputObject
    >;
  };
}
